dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

env:
  - DJANGO_VERSION='>=1.11,<2'
  - DJANGO_VERSION='>=2.0,<2.1'
  - DJANGO_VERSION='>=2.1,<2.2'
  - DJANGO_VERSION='>=2.2,<2.3'

notifications:
  email: false

install:
  - pip install -r .travis-requirements.txt
  - pip install Django$DJANGO_VERSION

script:
  - python runtests.py
