language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION='>=1.8,<1.9'
  - DJANGO_VERSION='>=1.9,<1.10'
  - DJANGO_VERSION='>=1.10,<1.11'

notifications:
  email: false

install:
  - pip install -r .travis-requirements.txt
  - pip install Django$DJANGO_VERSION

script:
  - python runtests.py

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION='>=1.9,<1.10'
    - python: "3.2"
      env: DJANGO_VERSION='>=1.10,<1.11'
    - python: "3.3"
      env: DJANGO_VERSION='>=1.9,<1.10'
    - python: "3.3"
      env: DJANGO_VERSION='>=1.10,<1.11'
